#!/usr/bin/env python3
"""Check that the generated Zig code compiles to constant-time machine code.

Every public function of each fiat-zig/src/*.zig file is compiled for a set of
targets and optimization modes, and the emitted assembly and optimized LLVM IR
are checked for:

  - conditional branches (and, on ARM and s390x, predicated loads and stores);
  - memory accesses whose address depends on the result of a conditional
    select (cmov/csel/set<cc>), as when a select of two arrays is compiled to a
    select of two pointers followed by a load (x86 and aarch64 assembly);
  - selects or phis of pointers, and getelementptr with a non-constant index
    (LLVM IR, all targets).

The functions generated by fiat-crypto are straight-line code that only reads
and writes at constant offsets from their pointer arguments, so any of the
above means the compiler introduced secret-dependent control flow or memory
accesses.

Usage: check.py [--zig ZIG] [--jobs N] [--self-test] [FILE.zig ...]

With --self-test, compile ct/bad.zig instead and check that its functions are
reported: all of them on x86 and aarch64, where the assembly is checked for
select-dependent addresses, and all but tableLookup elsewhere, where the
backend can turn its select of two loaded values into a load from a
select-dependent address that only the assembly shows.
"""

import argparse
import concurrent.futures
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# (name, zig target, extra flags, assembly dialect)
TARGETS_64 = [
    ("x86_64", "x86_64-linux", [], "x86"),
    ("x86_64_v3", "x86_64-linux", ["-mcpu=x86_64_v3"], "x86"),
    ("aarch64", "aarch64-linux", [], "aarch64"),
    ("riscv64", "riscv64-linux", [], "riscv"),
    ("powerpc64le", "powerpc64le-linux", [], "powerpc"),
    ("s390x", "s390x-linux", [], "s390x"),
    ("loongarch64", "loongarch64-linux", [], "loongarch"),
    ("wasm32", "wasm32-freestanding", [], "wasm"),
]
# Files that use 128-bit integers (all *_64 files, and p448_solinas_32) are
# meant for 64-bit targets only: on a 32-bit target, LLVM implements the
# multi-word carries with branches on e.g. riscv32.
TARGETS_32_ONLY = [
    ("x86", "x86-linux", [], "x86"),
    ("arm", "arm-linux-musleabihf", [], "arm"),
    ("thumb", "thumb-linux-musleabihf", [], "arm"),
    ("riscv32", "riscv32-linux", [], "riscv"),
]
MODES = ["ReleaseFast", "ReleaseSmall"]

ARM_CC = r"(?:eq|ne|cs|hs|cc|lo|mi|pl|vs|vc|hi|ls|ge|lt|gt|le)"
CONDITIONAL = {
    "x86": re.compile(r"^(?:j(?!mp$)[a-z]+|loop[a-z]*)$"),
    "aarch64": re.compile(r"^(?:b\.[a-z]+|cbn?z|tbn?z)$"),
    "arm": re.compile(
        r"^(?:b" + ARM_CC + r"|bl" + ARM_CC + r"|blx" + ARM_CC + r"|bx" + ARM_CC
        + r"|cbn?z|tb[bh]|(?:ldr|str|ldm|stm|pop|push)[a-z]*" + ARM_CC + r")(?:\.[wn])?$"
    ),
    "riscv": re.compile(r"^(?:c\.)?b(?:eq|ne|lt|ge|ltu|geu|eqz|nez|lez|gez|ltz|gtz|gt|le|gtu|leu)$"),
    "powerpc": re.compile(r"^b(?!$|a$|l$|la$|lr$|lrl$|ctr$|ctrl$)[a-z]*[+-]?$"),
    "s390x": re.compile(
        r"^(?:j(?!$|g$)[a-z]+|b(?!r$|ras$|rasl$|asr$)[a-z]*|c(?:l)?(?:g)?(?:r|i)?[jb][a-z]*"
        r"|(?:loc|stoc)(?:g|fh)?[a-z]*)$"
    ),
    "loongarch": re.compile(r"^(?:beq|bne|blt|bge|bltu|bgeu|beqz|bnez|bceqz|bcnez)$"),
    "wasm": re.compile(r"^(?:br_if|br_table|if|loop)$"),
}
# Predicated register-only moves are fine; only s390x load/store-on-condition
# with a memory operand counts.
S390X_REG_ONLY = re.compile(r"^loc(?:g|fh)?(?:r|hi|ghi|hhi)")


COMMENT = {"aarch64": ("//",), "arm": ("@", "//")}


def strip_comment(line, dialect):
    for marker in COMMENT.get(dialect, ("#",)):
        i = line.find(marker)
        if i >= 0:
            line = line[:i]
    return line.strip()


def split_functions(asm, dialect):
    """Map each function name to its list of (mnemonic, operands) pairs."""
    names = set(re.findall(r"^\s*\.type\s+\"?([^\",\s]+)\"?\s*,\s*[@%]function", asm, re.M))
    if dialect == "wasm":
        names |= set(re.findall(r"^\s*\.functype\s+(\S+)", asm, re.M))
    funcs = {}
    current = None
    for raw in asm.splitlines():
        line = strip_comment(raw, dialect)
        if not line:
            continue
        m = re.match(r'^"?([^":\s]+)"?:$', line)
        if m:
            label = m.group(1)
            if label in names:
                # Internal functions get a local .L prefix in some modes.
                current = funcs.setdefault(label[2:] if label.startswith(".L") else label, [])
            elif label.startswith(".Lfunc_end"):
                current = None
            continue
        if current is None or line.startswith("."):
            continue
        parts = line.split(None, 1)
        current.append((parts[0].lower(), parts[1] if len(parts) > 1 else ""))
    return funcs


def split_operands(ops):
    out, depth, cur = [], 0, ""
    for ch in ops:
        if ch in "[(":
            depth += 1
        elif ch in "])":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


X86_REG = {}
for full, aliases in {
    "rax": "al ah ax eax", "rbx": "bl bh bx ebx", "rcx": "cl ch cx ecx", "rdx": "dl dh dx edx",
    "rsi": "sil si esi", "rdi": "dil di edi", "rbp": "bpl bp ebp", "rsp": "spl sp esp",
}.items():
    X86_REG[full] = full
    for a in aliases.split():
        X86_REG[a] = full
for n in range(8, 16):
    for suffix in ("", "b", "w", "d"):
        X86_REG["r%d%s" % (n, suffix)] = "r%d" % n


def x86_regs(operand):
    regs = set()
    for tok in re.findall(r"[a-z][a-z0-9]*", operand.lower()):
        if tok in X86_REG:
            regs.add(X86_REG[tok])
        elif re.match(r"^[xyz]mm\d+$", tok):
            regs.add("v" + tok[3:])
    return regs


def aarch64_regs(operand):
    regs = set()
    for tok in re.findall(r"\b[a-z][a-z0-9]*\b", operand.lower()):
        m = re.match(r"^([xw])(\d+)$", tok)
        if m:
            regs.add("x" + m.group(2))
            continue
        m = re.match(r"^[vqdshb](\d+)$", tok)
        if m:
            regs.add("v" + m.group(1))
        elif tok in ("sp", "wsp"):
            regs.add("sp")
    return regs


def mem_operand(operand):
    m = re.search(r"\[([^\]]*)\]", operand)
    return m.group(1) if m else None


X86_PURE_WRITE = re.compile(r"^(?:mov[a-z]*|lea|pop|set[a-z]+|cmov[a-z]+|vmov[a-z]*|pextr[a-z]|vpextr[a-z])$")
X86_NO_DEST = re.compile(r"^(?:cmp|test|bt|push|call|ret|nop|j[a-z]*|ucomis[sd]|comis[sd])$")
X86_SELECT = re.compile(r"^(?:cmov[a-z]+|set[a-z]+)$")
AARCH64_SELECT = re.compile(r"^(?:csel|csinc|csinv|csneg|cset|csetm|cinc|cinv|cneg)$")
AARCH64_NO_DEST = re.compile(r"^(?:cmp|cmn|tst|ccmp|ccmn|st[a-z0-9]*|b|bl|blr|br|ret|b\..*|cbn?z|tbn?z|msr|prfm)$")
AARCH64_LOAD = re.compile(r"^ld[a-z0-9]*$")


def aarch64_slots(mnem, operands):
    """The stack slot (or other memory location) of each register operand of a
    load or store, so that a pair loads or stores each register separately."""
    m = re.match(r"^\[\s*(\w+)\s*(?:,\s*#(-?(?:0x)?[0-9a-f]+))?\s*\]!?$", operands[-1].strip())
    data = operands[:-1]
    if not m or len(data) < 1 or not all(re.match(r"^[xwqdsv]\d+", o) for o in data):
        return [(o, operands[-1]) for o in data]
    base, off = m.group(1), int(m.group(2) or "0", 0)
    size = {"x": 8, "w": 4, "q": 16, "d": 8, "s": 4}.get(data[0][0], 8)
    if re.match(r"^(?:ld|st)n?p(?:sw)?$", mnem):
        return [(o, (base, off + i * size)) for i, o in enumerate(data)]
    return [(o, (base, off)) for o in data]


def selector_addressing(insns, dialect):
    """Report memory accesses whose address is computed from a select result.

    Taint starts at conditional selects (and, on x86, at `sbb r, r` masks) and
    flows from source to destination registers, and through stores and loads
    of the same memory location (on aarch64, separately for each register of a
    pair).  The generated code never computes an address from data, so the
    tracking can be coarse without causing false positives.
    """
    regs = x86_regs if dialect == "x86" else aarch64_regs
    tainted, slots, problems = set(), set(), []
    for mnem, ops in insns:
        operands = split_operands(ops)
        mem = [mem_operand(o) for o in operands]
        for o, mo in zip(operands, mem):
            if mo is not None and mnem != "lea" and regs(mo) & tainted:
                problems.append("address depends on a select: %s %s" % (mnem, ops))
        if dialect == "x86":
            if X86_NO_DEST.match(mnem) or not operands:
                continue
            dest, srcs = operands[0], operands[1:]
            if mem[0] is not None:
                if any(regs(s) & tainted for s in srcs):
                    slots.add(mem[0])
                else:
                    slots.discard(mem[0])
                continue
            if len(operands) == 2 and operands[0] == operands[1] and mnem in ("xor", "sub", "pxor", "vpxor"):
                tainted -= regs(dest)
                continue
            src_regs, from_slot = set(), False
            for s, ms in zip(srcs, mem[1:]):
                if ms is not None:
                    from_slot |= ms in slots
                else:
                    src_regs |= regs(s)
            if not X86_PURE_WRITE.match(mnem):
                src_regs |= regs(dest)
            dests = regs(dest)
            if mnem in ("mul", "imul", "div", "idiv") and len(operands) == 1:
                dests, src_regs = {"rax", "rdx"}, src_regs | {"rax", "rdx"}
            elif mnem == "mulx" and len(operands) == 3:
                dests = regs(operands[0]) | regs(operands[1])
                src_regs = regs(operands[2]) | {"rdx"}
            elif mnem == "xchg":
                dests = regs(operands[0]) | regs(operands[1])
            taint = (X86_SELECT.match(mnem) or (mnem == "sbb" and operands[0] == operands[1])
                     or from_slot or bool(src_regs & tainted))
        else:
            if AARCH64_NO_DEST.match(mnem) or not operands:
                if mnem.startswith("st") and mem[-1] is not None:
                    for o, slot in aarch64_slots(mnem, operands):
                        if regs(o) & tainted:
                            slots.add(slot)
                        else:
                            slots.discard(slot)
                continue
            if AARCH64_LOAD.match(mnem) and mem[-1] is not None:
                for o, slot in aarch64_slots(mnem, operands):
                    if slot in slots:
                        tainted |= regs(o)
                    else:
                        tainted -= regs(o)
                continue
            dests = regs(operands[0])
            src_regs = set().union(*(regs(o) for o in operands[1:])) if len(operands) > 1 else set()
            if mnem in ("movk", "bfi", "bfxil", "bif", "bit", "bsl", "ins"):
                src_regs |= dests
            taint = AARCH64_SELECT.match(mnem) or bool(src_regs & tainted)
        if taint:
            tainted |= dests
        else:
            tainted -= dests
    return problems


def check_asm(asm, dialect):
    problems = {}
    for name, insns in split_functions(asm, dialect).items():
        found = []
        cond = CONDITIONAL[dialect]
        for mnem, ops in insns:
            if cond.match(mnem):
                if dialect == "s390x" and (S390X_REG_ONLY.match(mnem) or (mnem.startswith(("loc", "stoc")) and "(" not in ops)):
                    continue
                found.append("conditional branch or predicated memory access: %s %s" % (mnem, ops))
        if dialect in ("x86", "aarch64"):
            found += selector_addressing(insns, dialect)
        if found:
            problems[name] = found
    return problems


IR_DEFINE = re.compile(r"^define [^@]*@\"?([^\"(]+)\"?\(")
IR_GEP = re.compile(r"getelementptr (?:inbounds |nuw |nusw |inrange\(\S+\) )*[^,]+, ptr %[\w.\"-]+((?:, [^,]+)*)")


def check_ir(ir):
    problems = {}
    current, found = None, []
    for line in ir.splitlines():
        m = IR_DEFINE.match(line)
        if m:
            current, found = m.group(1), []
            continue
        if current is None:
            continue
        if line.startswith("}"):
            if found:
                problems[current] = found
            current = None
            continue
        s = line.split(", !dbg")[0].strip()
        if re.search(r"\bselect (?:i1|<\d+ x i1>) [^,]+, ptr\b", s) or re.search(r"\bphi ptr\b", s):
            found.append("select of pointers: " + s)
        elif re.search(r"\b(?:br i1|switch|indirectbr|callbr)\b", s):
            found.append("conditional control flow: " + s)
        else:
            g = IR_GEP.search(s)
            if g and re.search(r"(?:^|, )\S+ %", g.group(1)):
                found.append("variable getelementptr index: " + s)
    return problems


def compile_one(zig, src, target, mode, workdir):
    name, triple, flags, dialect = target
    base = os.path.join(workdir, "%s-%s-%s" % (os.path.basename(src)[:-4], name, mode))
    cmd = [zig, "build-obj", "-O", mode, "-target", triple, *flags, "-fstrip",
           "--dep", "fiat", "-Mroot=" + os.path.join(HERE, "export.zig"), "-Mfiat=" + src,
           "-femit-asm=" + base + ".s", "-femit-llvm-ir=" + base + ".ll", "-fno-emit-bin",
           "--cache-dir", os.path.join(workdir, "cache"), "--global-cache-dir", os.path.join(workdir, "cache")]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        return (src, name, mode), None, res.stderr
    with open(base + ".s") as f:
        problems = check_asm(f.read(), dialect)
    with open(base + ".ll") as f:
        for fn, found in check_ir(f.read()).items():
            problems.setdefault(fn, []).extend(found)
    return (src, name, mode), problems, None


def jobs_for(files):
    for src in files:
        with open(src) as f:
            wide = re.search(r"\b[ui]128\b", f.read())
        targets = TARGETS_64 + ([] if wide else TARGETS_32_ONLY)
        for target in targets:
            for mode in MODES:
                yield src, target, mode


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zig", default="zig")
    ap.add_argument("--jobs", type=int, default=os.cpu_count())
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("files", nargs="*")
    args = ap.parse_args()

    if args.self_test:
        files = [os.path.join(HERE, "bad.zig")]
    elif args.files:
        files = [os.path.abspath(f) for f in args.files]
    else:
        srcdir = os.path.join(ROOT, "src")
        files = sorted(os.path.join(srcdir, f) for f in os.listdir(srcdir)
                       if f.endswith(".zig") and f != "main.zig")

    failures = 0  # number of (configuration, function) pairs with a problem
    with tempfile.TemporaryDirectory() as workdir, \
            concurrent.futures.ThreadPoolExecutor(args.jobs) as pool:
        results = list(pool.map(lambda j: compile_one(args.zig, *j, workdir), jobs_for(files)))
    for (src, target, mode), problems, err in results:
        where = "%s (%s, %s)" % (os.path.relpath(src, ROOT), target, mode)
        if err is not None:
            print("error: failed to compile %s:\n%s" % (where, err))
            failures += 1
        elif args.self_test:
            expected = {"bad.selectArray", "bad.collatzSteps"}
            if dict((t[0], t[3]) for t in TARGETS_64 + TARGETS_32_ONLY)[target] in ("x86", "aarch64"):
                expected.add("bad.tableLookup")
            missed = sorted(expected - set(problems))
            if missed:
                print("error: %s: not reported: %s" % (where, ", ".join(missed)))
                failures += 1
        else:
            for fn, found in sorted(problems.items()):
                for p in found:
                    print("error: %s: %s: %s" % (where, fn, p))
                failures += 1
    print("%d configurations checked, %d failures" % (len(results), failures))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
