/* Autogenerated: 'src/ExtractionOCaml/dettman_multiplication' --inline --static --use-value-barrier secp256k1_dettman 32 10 22 '2^256 - 4294968273' mul32 square32 */
/* curve description: secp256k1_dettman */
/* machine_wordsize = 32 (from "32") */
/* requested operations: mul32, square32 */
/* n = 10 (from "10") */
/* last_limb_width = 22 (from "22") */
/* s-c = 2^256 - [(1, 4294968273)] (from "2^256 - 4294968273") */
/* inbounds_multiplier: None (from "") */
/*  */
/* Computed values: */
/*  */
/*  */

#include <stdint.h>
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_SECP256K1_DETTMAN_FIAT_INLINE __inline__
#else
#  define FIAT_SECP256K1_DETTMAN_FIAT_INLINE
#endif

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_secp256k1_dettman_mul32 multiplies two field elements.
 *
 * Postconditions:
 *   eval out1 mod 115792089237316195423570985008687907853269984665640564039457584007908834671663 = (eval arg1 * eval arg2) mod 115792089237316195423570985008687907853269984665640564039457584007908834671663
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7ffffe]]
 *   arg2: [[0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7ffffe]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x5fffff]]
 */
static FIAT_SECP256K1_DETTMAN_FIAT_INLINE void fiat_secp256k1_dettman_mul32(uint32_t out1[10], const uint32_t arg1[10], const uint32_t arg2[10]) {
  uint64_t x1;
  int64_t x2;
  int64_t x3;
  int64_t x4;
  int64_t x5;
  int64_t x6;
  int64_t x7;
  int64_t x8;
  int64_t x9;
  int64_t x10;
  int64_t x11;
  int64_t x12;
  int64_t x13;
  int64_t x14;
  int64_t x15;
  int64_t x16;
  int64_t x17;
  int64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint32_t x22;
  uint64_t x23;
  uint64_t x24;
  uint32_t x25;
  uint64_t x26;
  uint32_t x27;
  uint64_t x28;
  uint64_t x29;
  uint32_t x30;
  uint64_t x31;
  uint64_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  uint64_t x36;
  uint64_t x37;
  uint32_t x38;
  uint64_t x39;
  uint32_t x40;
  uint32_t x41;
  uint64_t x42;
  uint64_t x43;
  uint32_t x44;
  uint64_t x45;
  uint64_t x46;
  uint32_t x47;
  uint64_t x48;
  uint64_t x49;
  uint32_t x50;
  uint64_t x51;
  uint64_t x52;
  uint32_t x53;
  uint64_t x54;
  uint64_t x55;
  uint32_t x56;
  uint64_t x57;
  uint64_t x58;
  uint32_t x59;
  uint64_t x60;
  uint64_t x61;
  uint32_t x62;
  uint64_t x63;
  uint64_t x64;
  uint32_t x65;
  uint64_t x66;
  uint64_t x67;
  uint32_t x68;
  uint64_t x69;
  uint64_t x70;
  uint32_t x71;
  uint64_t x72;
  uint32_t x73;
  uint64_t x74;
  uint64_t x75;
  uint32_t x76;
  uint64_t x77;
  uint32_t x78;
  uint32_t x79;
  uint64_t x80;
  uint32_t x81;
  uint32_t x82;
  uint32_t x83;
  x1 = ((uint64_t)(arg1[9]) * (arg2[9]));
  x2 = (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[8])) * (int32_t)((int32_t)(arg2[8]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - (((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7])))));
  x3 = (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[7])) * (int32_t)((int32_t)(arg2[7]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - ((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6])))));
  x4 = (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[7])) * (int32_t)((int32_t)(arg2[7]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[6])) * (int32_t)((int32_t)(arg2[6]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - (((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))))));
  x5 = (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[6])) * (int32_t)((int32_t)(arg2[6]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[5])) * (int32_t)((int32_t)(arg2[5]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - ((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))))));
  x6 = (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[6])) * (int32_t)((int32_t)(arg2[6]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[5])) * (int32_t)((int32_t)(arg2[5]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[4])) * (int32_t)((int32_t)(arg2[4]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - (((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3])))))));
  x7 = (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[5])) * (int32_t)((int32_t)(arg2[5]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[4])) * (int32_t)((int32_t)(arg2[4]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - ((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2])))))));
  x8 = (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[5])) * (int32_t)((int32_t)(arg2[5]) - (arg2[6]))) + (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[4])) * (int32_t)((int32_t)(arg2[4]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - (((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))))))));
  x9 = (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[4])) * (int32_t)((int32_t)(arg2[4]) - (arg2[6]))) + (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[9]))) + (int64_t)((int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1) - ((uint64_t)(arg1[0]) * (arg2[0])))))));
  x10 = (((int64_t)(int32_t)((int32_t)(arg1[5]) - (arg1[4])) * (int32_t)((int32_t)(arg2[4]) - (arg2[5]))) + (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[6]))) + (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[8]))) + (((int64_t)(int32_t)((int32_t)(arg1[9]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[9]))) + (int64_t)(((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8]))) + x1))))));
  x11 = (((int64_t)(int32_t)((int32_t)(arg1[5]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[5]))) + (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[6]))) + (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[7]))) + (((int64_t)(int32_t)((int32_t)(arg1[8]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[8]))) + (int64_t)((((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7]))) + ((uint64_t)(arg1[8]) * (arg2[8])))))));
  x12 = (((int64_t)(int32_t)((int32_t)(arg1[4]) - (arg1[3])) * (int32_t)((int32_t)(arg2[3]) - (arg2[4]))) + (((int64_t)(int32_t)((int32_t)(arg1[5]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[5]))) + (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[6]))) + (((int64_t)(int32_t)((int32_t)(arg1[7]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[7]))) + (int64_t)(((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))) + ((uint64_t)(arg1[7]) * (arg2[7])))))));
  x13 = (((int64_t)(int32_t)((int32_t)(arg1[4]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[4]))) + (((int64_t)(int32_t)((int32_t)(arg1[5]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[5]))) + (((int64_t)(int32_t)((int32_t)(arg1[6]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[6]))) + (int64_t)((((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))) + ((uint64_t)(arg1[6]) * (arg2[6]))))));
  x14 = (((int64_t)(int32_t)((int32_t)(arg1[3]) - (arg1[2])) * (int32_t)((int32_t)(arg2[2]) - (arg2[3]))) + (((int64_t)(int32_t)((int32_t)(arg1[4]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[4]))) + (((int64_t)(int32_t)((int32_t)(arg1[5]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[5]))) + (int64_t)(((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4]))) + ((uint64_t)(arg1[5]) * (arg2[5]))))));
  x15 = (((int64_t)(int32_t)((int32_t)(arg1[3]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[3]))) + (((int64_t)(int32_t)((int32_t)(arg1[4]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[4]))) + (int64_t)((((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3]))) + ((uint64_t)(arg1[4]) * (arg2[4])))));
  x16 = (((int64_t)(int32_t)((int32_t)(arg1[2]) - (arg1[1])) * (int32_t)((int32_t)(arg2[1]) - (arg2[2]))) + (((int64_t)(int32_t)((int32_t)(arg1[3]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[3]))) + (int64_t)(((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))) + ((uint64_t)(arg1[3]) * (arg2[3])))));
  x17 = (((int64_t)(int32_t)((int32_t)(arg1[2]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[2]))) + (int64_t)((((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))) + ((uint64_t)(arg1[2]) * (arg2[2]))));
  x18 = (((int64_t)(int32_t)((int32_t)(arg1[1]) - (arg1[0])) * (int32_t)((int32_t)(arg2[0]) - (arg2[1]))) + (int64_t)(((uint64_t)(arg1[0]) * (arg2[0])) + ((uint64_t)(arg1[1]) * (arg2[1]))));
  x19 = ((uint64_t)(arg1[0]) * (arg2[0]));
  x20 = (x2 & UINT64_C(0x7ffffffffffffff));
  x21 = (x20 >> 26);
  x22 = (uint32_t)(x20 & UINT32_C(0x3ffffff));
  x23 = ((x12 & UINT64_C(0x1fffffffffffffff)) + ((uint64_t)x22 * UINT16_C(0x3d10)));
  x24 = (x23 >> 26);
  x25 = (uint32_t)(x23 & UINT32_C(0x3ffffff));
  x26 = (x21 + x1);
  x27 = (uint32_t)(x26 >> 32);
  x28 = ((x24 + ((x11 & UINT64_C(0x3fffffffffffffff)) + ((uint64_t)x22 << 10))) + ((uint64_t)(uint32_t)x26 * UINT16_C(0x3d10)));
  x29 = (x28 >> 26);
  x30 = (uint32_t)(x28 & UINT32_C(0x3ffffff));
  x31 = ((x29 + ((x10 & UINT64_C(0x3fffffffffffffff)) + ((uint64_t)(uint32_t)x26 << 10))) + ((uint64_t)x27 * UINT32_C(0xf4400)));
  x32 = (x31 >> 26);
  x33 = (uint32_t)(x31 & UINT32_C(0x3ffffff));
  x34 = (x33 >> 22);
  x35 = (x33 & UINT32_C(0x3fffff));
  x36 = (x32 + ((x9 & UINT64_C(0x3fffffffffffffff)) + (x27 << 16)));
  x37 = (x36 >> 26);
  x38 = (uint32_t)(x36 & UINT32_C(0x3ffffff));
  x39 = (x19 + ((uint64_t)(x34 + (x38 << 4)) * UINT16_C(0x3d1)));
  x40 = (uint32_t)(x39 >> 26);
  x41 = (uint32_t)(x39 & UINT32_C(0x3ffffff));
  x42 = (x37 + (x8 & UINT64_C(0x1fffffffffffffff)));
  x43 = (x42 >> 26);
  x44 = (uint32_t)(x42 & UINT32_C(0x3ffffff));
  x45 = ((x40 + ((x18 & UINT64_C(0x7ffffffffffffff)) + ((uint64_t)(x34 + (x38 << 4)) << 6))) + ((uint64_t)x44 * UINT16_C(0x3d10)));
  x46 = (x45 >> 26);
  x47 = (uint32_t)(x45 & UINT32_C(0x3ffffff));
  x48 = (x43 + (x7 & UINT64_C(0x1fffffffffffffff)));
  x49 = (x48 >> 26);
  x50 = (uint32_t)(x48 & UINT32_C(0x3ffffff));
  x51 = ((x46 + ((x17 & UINT64_C(0xfffffffffffffff)) + ((uint64_t)x44 << 10))) + ((uint64_t)x50 * UINT16_C(0x3d10)));
  x52 = (x51 >> 26);
  x53 = (uint32_t)(x51 & UINT32_C(0x3ffffff));
  x54 = (x49 + (x6 & UINT64_C(0x1fffffffffffffff)));
  x55 = (x54 >> 26);
  x56 = (uint32_t)(x54 & UINT32_C(0x3ffffff));
  x57 = ((x52 + ((x16 & UINT64_C(0xfffffffffffffff)) + ((uint64_t)x50 << 10))) + ((uint64_t)x56 * UINT16_C(0x3d10)));
  x58 = (x57 >> 26);
  x59 = (uint32_t)(x57 & UINT32_C(0x3ffffff));
  x60 = (x55 + (x5 & UINT64_C(0x1fffffffffffffff)));
  x61 = (x60 >> 26);
  x62 = (uint32_t)(x60 & UINT32_C(0x3ffffff));
  x63 = ((x58 + ((x15 & UINT64_C(0x1fffffffffffffff)) + ((uint64_t)x56 << 10))) + ((uint64_t)x62 * UINT16_C(0x3d10)));
  x64 = (x63 >> 26);
  x65 = (uint32_t)(x63 & UINT32_C(0x3ffffff));
  x66 = (x61 + (x4 & UINT64_C(0xfffffffffffffff)));
  x67 = (x66 >> 26);
  x68 = (uint32_t)(x66 & UINT32_C(0x3ffffff));
  x69 = ((x64 + ((x14 & UINT64_C(0x1fffffffffffffff)) + ((uint64_t)x62 << 10))) + ((uint64_t)x68 * UINT16_C(0x3d10)));
  x70 = (x69 >> 26);
  x71 = (uint32_t)(x69 & UINT32_C(0x3ffffff));
  x72 = (x67 + (x3 & UINT64_C(0xfffffffffffffff)));
  x73 = (uint32_t)(x72 >> 32);
  x74 = ((x70 + ((x13 & UINT64_C(0x1fffffffffffffff)) + ((uint64_t)x68 << 10))) + ((uint64_t)(uint32_t)x72 * UINT16_C(0x3d10)));
  x75 = (x74 >> 26);
  x76 = (uint32_t)(x74 & UINT32_C(0x3ffffff));
  x77 = ((x75 + (x25 + ((uint64_t)(uint32_t)x72 << 10))) + ((uint64_t)x73 * UINT32_C(0xf4400)));
  x78 = (uint32_t)(x77 >> 26);
  x79 = (uint32_t)(x77 & UINT32_C(0x3ffffff));
  x80 = (x78 + (x30 + ((uint64_t)x73 << 16)));
  x81 = (uint32_t)(x80 >> 26);
  x82 = (uint32_t)(x80 & UINT32_C(0x3ffffff));
  x83 = (x81 + x35);
  out1[0] = x41;
  out1[1] = x47;
  out1[2] = x53;
  out1[3] = x59;
  out1[4] = x65;
  out1[5] = x71;
  out1[6] = x76;
  out1[7] = x79;
  out1[8] = x82;
  out1[9] = x83;
}

/*
 * The function fiat_secp256k1_dettman_square32 squares a field element.
 *
 * Postconditions:
 *   eval out1 mod 115792089237316195423570985008687907853269984665640564039457584007908834671663 = (eval arg1 * eval arg1) mod 115792089237316195423570985008687907853269984665640564039457584007908834671663
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7ffffe]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x7fffffe], [0x0 ~> 0x5fffff]]
 */
static FIAT_SECP256K1_DETTMAN_FIAT_INLINE void fiat_secp256k1_dettman_square32(uint32_t out1[10], const uint32_t arg1[10]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint64_t x10;
  uint32_t x11;
  uint32_t x12;
  uint64_t x13;
  uint32_t x14;
  uint32_t x15;
  uint64_t x16;
  uint32_t x17;
  uint64_t x18;
  uint32_t x19;
  uint32_t x20;
  uint64_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint64_t x26;
  uint32_t x27;
  uint32_t x28;
  uint64_t x29;
  uint32_t x30;
  uint32_t x31;
  uint64_t x32;
  uint32_t x33;
  uint32_t x34;
  uint64_t x35;
  uint32_t x36;
  uint32_t x37;
  uint64_t x38;
  uint32_t x39;
  uint32_t x40;
  uint64_t x41;
  uint32_t x42;
  uint32_t x43;
  uint64_t x44;
  uint32_t x45;
  uint32_t x46;
  uint64_t x47;
  uint32_t x48;
  uint32_t x49;
  uint64_t x50;
  uint32_t x51;
  uint32_t x52;
  uint64_t x53;
  uint32_t x54;
  uint32_t x55;
  uint64_t x56;
  uint32_t x57;
  uint32_t x58;
  uint64_t x59;
  uint32_t x60;
  uint32_t x61;
  uint64_t x62;
  uint32_t x63;
  uint64_t x64;
  uint32_t x65;
  uint32_t x66;
  uint64_t x67;
  uint32_t x68;
  uint32_t x69;
  uint64_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  x1 = ((arg1[8]) * 0x2);
  x2 = ((arg1[7]) * 0x2);
  x3 = ((arg1[6]) * 0x2);
  x4 = ((arg1[5]) * 0x2);
  x5 = ((arg1[4]) * 0x2);
  x6 = ((arg1[3]) * 0x2);
  x7 = ((arg1[2]) * 0x2);
  x8 = ((arg1[1]) * 0x2);
  x9 = ((arg1[0]) * 0x2);
  x10 = ((uint64_t)x1 * (arg1[9]));
  x11 = (uint32_t)(x10 >> 26);
  x12 = (uint32_t)(x10 & UINT32_C(0x3ffffff));
  x13 = ((((uint64_t)x9 * (arg1[7])) + (((uint64_t)x8 * (arg1[6])) + (((uint64_t)x7 * (arg1[5])) + ((uint64_t)x6 * (arg1[4]))))) + ((uint64_t)x12 * UINT16_C(0x3d10)));
  x14 = (uint32_t)(x13 >> 26);
  x15 = (uint32_t)(x13 & UINT32_C(0x3ffffff));
  x16 = (x11 + ((uint64_t)(arg1[9]) * (arg1[9])));
  x17 = (uint32_t)(x16 >> 32);
  x18 = ((x14 + ((((uint64_t)x9 * (arg1[8])) + (((uint64_t)x8 * (arg1[7])) + (((uint64_t)x7 * (arg1[6])) + (((uint64_t)x6 * (arg1[5])) + ((uint64_t)(arg1[4]) * (arg1[4])))))) + ((uint64_t)x12 << 10))) + ((uint64_t)(uint32_t)x16 * UINT16_C(0x3d10)));
  x19 = (uint32_t)(x18 >> 26);
  x20 = (uint32_t)(x18 & UINT32_C(0x3ffffff));
  x21 = ((x19 + ((((uint64_t)x9 * (arg1[9])) + (((uint64_t)x8 * (arg1[8])) + (((uint64_t)x7 * (arg1[7])) + (((uint64_t)x6 * (arg1[6])) + ((uint64_t)x5 * (arg1[5])))))) + ((uint64_t)(uint32_t)x16 << 10))) + ((uint64_t)x17 * UINT32_C(0xf4400)));
  x22 = (uint32_t)(x21 >> 26);
  x23 = (uint32_t)(x21 & UINT32_C(0x3ffffff));
  x24 = (x23 >> 22);
  x25 = (x23 & UINT32_C(0x3fffff));
  x26 = (x22 + ((((uint64_t)x8 * (arg1[9])) + (((uint64_t)x7 * (arg1[8])) + (((uint64_t)x6 * (arg1[7])) + (((uint64_t)x5 * (arg1[6])) + ((uint64_t)(arg1[5]) * (arg1[5])))))) + (x17 << 16)));
  x27 = (uint32_t)(x26 >> 26);
  x28 = (uint32_t)(x26 & UINT32_C(0x3ffffff));
  x29 = (((uint64_t)(arg1[0]) * (arg1[0])) + ((uint64_t)(x24 + (x28 << 4)) * UINT16_C(0x3d1)));
  x30 = (uint32_t)(x29 >> 26);
  x31 = (uint32_t)(x29 & UINT32_C(0x3ffffff));
  x32 = (x27 + (((uint64_t)x7 * (arg1[9])) + (((uint64_t)x6 * (arg1[8])) + (((uint64_t)x5 * (arg1[7])) + ((uint64_t)x4 * (arg1[6]))))));
  x33 = (uint32_t)(x32 >> 26);
  x34 = (uint32_t)(x32 & UINT32_C(0x3ffffff));
  x35 = ((x30 + (((uint64_t)x9 * (arg1[1])) + ((uint64_t)(x24 + (x28 << 4)) << 6))) + ((uint64_t)x34 * UINT16_C(0x3d10)));
  x36 = (uint32_t)(x35 >> 26);
  x37 = (uint32_t)(x35 & UINT32_C(0x3ffffff));
  x38 = (x33 + (((uint64_t)x6 * (arg1[9])) + (((uint64_t)x5 * (arg1[8])) + (((uint64_t)x4 * (arg1[7])) + ((uint64_t)(arg1[6]) * (arg1[6]))))));
  x39 = (uint32_t)(x38 >> 26);
  x40 = (uint32_t)(x38 & UINT32_C(0x3ffffff));
  x41 = ((x36 + ((((uint64_t)x9 * (arg1[2])) + ((uint64_t)(arg1[1]) * (arg1[1]))) + ((uint64_t)x34 << 10))) + ((uint64_t)x40 * UINT16_C(0x3d10)));
  x42 = (uint32_t)(x41 >> 26);
  x43 = (uint32_t)(x41 & UINT32_C(0x3ffffff));
  x44 = (x39 + (((uint64_t)x5 * (arg1[9])) + (((uint64_t)x4 * (arg1[8])) + ((uint64_t)x3 * (arg1[7])))));
  x45 = (uint32_t)(x44 >> 26);
  x46 = (uint32_t)(x44 & UINT32_C(0x3ffffff));
  x47 = ((x42 + ((((uint64_t)x9 * (arg1[3])) + ((uint64_t)x8 * (arg1[2]))) + ((uint64_t)x40 << 10))) + ((uint64_t)x46 * UINT16_C(0x3d10)));
  x48 = (uint32_t)(x47 >> 26);
  x49 = (uint32_t)(x47 & UINT32_C(0x3ffffff));
  x50 = (x45 + (((uint64_t)x4 * (arg1[9])) + (((uint64_t)x3 * (arg1[8])) + ((uint64_t)(arg1[7]) * (arg1[7])))));
  x51 = (uint32_t)(x50 >> 26);
  x52 = (uint32_t)(x50 & UINT32_C(0x3ffffff));
  x53 = ((x48 + ((((uint64_t)x9 * (arg1[4])) + (((uint64_t)x8 * (arg1[3])) + ((uint64_t)(arg1[2]) * (arg1[2])))) + ((uint64_t)x46 << 10))) + ((uint64_t)x52 * UINT16_C(0x3d10)));
  x54 = (uint32_t)(x53 >> 26);
  x55 = (uint32_t)(x53 & UINT32_C(0x3ffffff));
  x56 = (x51 + (((uint64_t)x3 * (arg1[9])) + ((uint64_t)x2 * (arg1[8]))));
  x57 = (uint32_t)(x56 >> 26);
  x58 = (uint32_t)(x56 & UINT32_C(0x3ffffff));
  x59 = ((x54 + ((((uint64_t)x9 * (arg1[5])) + (((uint64_t)x8 * (arg1[4])) + ((uint64_t)x7 * (arg1[3])))) + ((uint64_t)x52 << 10))) + ((uint64_t)x58 * UINT16_C(0x3d10)));
  x60 = (uint32_t)(x59 >> 26);
  x61 = (uint32_t)(x59 & UINT32_C(0x3ffffff));
  x62 = (x57 + (((uint64_t)x2 * (arg1[9])) + ((uint64_t)(arg1[8]) * (arg1[8]))));
  x63 = (uint32_t)(x62 >> 32);
  x64 = ((x60 + ((((uint64_t)x9 * (arg1[6])) + (((uint64_t)x8 * (arg1[5])) + (((uint64_t)x7 * (arg1[4])) + ((uint64_t)(arg1[3]) * (arg1[3]))))) + ((uint64_t)x58 << 10))) + ((uint64_t)(uint32_t)x62 * UINT16_C(0x3d10)));
  x65 = (uint32_t)(x64 >> 26);
  x66 = (uint32_t)(x64 & UINT32_C(0x3ffffff));
  x67 = ((x65 + (x15 + ((uint64_t)(uint32_t)x62 << 10))) + ((uint64_t)x63 * UINT32_C(0xf4400)));
  x68 = (uint32_t)(x67 >> 26);
  x69 = (uint32_t)(x67 & UINT32_C(0x3ffffff));
  x70 = (x68 + (x20 + ((uint64_t)x63 << 16)));
  x71 = (uint32_t)(x70 >> 26);
  x72 = (uint32_t)(x70 & UINT32_C(0x3ffffff));
  x73 = (x71 + x25);
  out1[0] = x31;
  out1[1] = x37;
  out1[2] = x43;
  out1[3] = x49;
  out1[4] = x55;
  out1[5] = x61;
  out1[6] = x66;
  out1[7] = x69;
  out1[8] = x72;
  out1[9] = x73;
}
