# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "submodules"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "sp2019latest"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
      - "sp2019latest"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "sp2019latest"
    schedule:
      interval: "daily"
    labels:
      - "submodules"
      - "sp2019latest"
