FIATCRYPTO_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
FIATCRYPTO_VFILES := $(call rwildcard,$(FIATCRYPTO_DIR),*.v)
FIATCRYPTO_COQDEPFLAGS := -R $(FIATCRYPTO_DIR) Crypto
FIATCRYPTO_REQUIREFLAGS := -Q $(O)/$(FIATCRYPTO_DIR) Crypto

FIATCRYPTO_COQFLAGS := $(COQPRIME_REQUIREFLAGS) $(REWRITER_REQUIREFLAGS) $(COQUTIL_REQUIREFLAGS) $(BEDROCK_REQUIREFLAGS) $(BEDROCK_EXAMPLES_REQUIREFLAGS) $(RISCV_REQUIREFLAGS) $(BEDROCK_COMPILER_REQUIREFLAGS) $(BEDROCK_COMPILER_EXAMPLES_REQUIREFLAGS) $(RUPICOLA_REQUIREFLAGS) -R $(O)/$(FIATCRYPTO_DIR) Crypto -w -deprecated-from-Coq,-deprecated-since-9.0,-deprecated-since-8.20
$(O)/$(FIATCRYPTO_DIR)/%.vo: private COQFLAGS += $(FIATCRYPTO_COQFLAGS)
$(O)/$(FIATCRYPTO_DIR)/%.vos: private COQFLAGS += $(FIATCRYPTO_COQFLAGS)
$(O)/$(FIATCRYPTO_DIR)/%.vok: private COQFLAGS += $(FIATCRYPTO_COQFLAGS)
$(FIATCRYPTO_DIR)/_CoqProject: private COQFLAGS += $(FIATCRYPTO_COQFLAGS)
