name: Test Generated Java

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test-java:

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 8
        distribution: 'zulu'
    - name: make only-test-java-files
      run: make only-test-java-files EXTERNAL_DEPENDENCIES=1
    - name: make documentation
      run: make only-javadoc EXTERNAL_DEPENDENCIES=1
    - uses: actions/upload-artifact@v3
      with:
        name: fiat-javadoc
        path: fiat-java/doc
