name: Test Generated Java

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: make only-test-java-files
      run: make only-test-java-files EXTERNAL_DEPENDENCIES=1
    - name: make documentation
      run: make only-javadoc EXTERNAL_DEPENDENCIES=1
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: fiat-javadoc
        path: fiat-java/doc
